### ISSUE TITLE
Update Figma for the milestone

### ISSUE THREAD

**Issue by 0marwa** [feedme-swent-epfl/feedme-android#172]
**Updating the Figma to match the current EPIC Stories for the MS3**

- [x] Adding the search bar UI
- [x] Removing time & difficulty from all recipe displays + from Recipe Data Class
- [x] Removing time from comments
- [x] Implement Edit Recipe Screen
- [x] Implement Followers and Following Screen
